name: "DYS"
mode: "dev"
port: 8080
version: "v0.0.1"
start_time: "2024-07-01"
machine_id: 1

auth:
  jwt_expire: 8760

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "47.116.168.248"
  port: 3306
  user: "root"
  password: "cfcf1103"
  dbname: "DYS"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: "47.116.168.248"
  port: 6379
  db: 0
  password: ""
  pool_size: 100